# yaml (Yaml Ain't Markup Language')
server:
  port: 9025

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  datasource:
    url: jdbc:mariadb://Ibbinstance.cjraovccfifn.us-west-1.rds.amazonaws.com:3306/indeeddb
    username: indeeduser
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
